"""Fork-only evidence: geometry audit and generated-report checks, not solver fixes.

Generated by ChatGPT. No upstream writes, no CFD solve, no optimization run.
"""
from collections import Counter, defaultdict
import hashlib
import json
import math
from pathlib import Path
import re
import subprocess
import sys
from urllib.request import urlopen

OUT = Path('wave13-results').resolve()
MESH_COMMIT = '790c80ec5b543487b5f8ecf8bb0f0e4d2cc67f3f'
MESH_PATH = 'euler/biparabolic/mesh_BIPARABOLIC_sup.su2'
MESH_BLOB = 'e1e8416171bbbab6b12ca1d1a8b8c8470ae9bff9'
OPENMDAO_COMMIT = '176ac87acb1800fa4e1b5883b4bb73e4890cfe24'


def save(name, data):
    OUT.mkdir(exist_ok=True)
    (OUT / name).write_text(json.dumps(data, indent=2) + '\n')


def parse_mesh(text):
    """Read the subset of serial 2-D SU2 mesh syntax used by this fixture."""
    lines = iter(line.split('%', 1)[0].strip() for line in text.splitlines()
                 if line.split('%', 1)[0].strip())
    points, cells, markers = {}, [], {}
    dimension = None
    for line in lines:
        if '=' not in line:
            raise ValueError('Unexpected mesh record: ' + line[:80])
        key, value = (part.strip() for part in line.split('=', 1))
        if key == 'NDIME':
            dimension = int(value)
            if dimension != 2:
                raise ValueError('This audit only supports 2-D meshes')
        elif key == 'NELEM':
            for _ in range(int(value.split()[0])):
                fields = next(lines).split()
                width = {5: 3, 9: 4}.get(int(fields[0]))
                if width is None:
                    raise ValueError('Unsupported volume element type')
                cells.append(tuple(map(int, fields[1:1+width])))
        elif key == 'NPOIN':
            for index in range(int(value.split()[0])):
                fields = next(lines).split()
                node = int(fields[2]) if len(fields) > 2 else index
                if node in points:
                    raise ValueError('Duplicate point ID')
                xy = tuple(map(float, fields[:2]))
                if len(xy) != 2 or not all(map(math.isfinite, xy)):
                    raise ValueError('Nonfinite/incomplete point coordinate')
                points[node] = xy
        elif key == 'NMARK':
            for _ in range(int(value)):
                name_line = next(lines)
                size_line = next(lines)
                if not name_line.startswith('MARKER_TAG=') or not size_line.startswith('MARKER_ELEMS='):
                    raise ValueError('Unexpected marker header')
                name = name_line.split('=', 1)[1].strip()
                if name in markers:
                    raise ValueError('Duplicate marker name')
                edges = []
                for _ in range(int(size_line.split('=', 1)[1])):
                    fields = next(lines).split()
                    if int(fields[0]) != 3:
                        raise ValueError('Expected line boundary elements')
                    edges.append(tuple(map(int, fields[1:3])))
                markers[name] = edges
        elif key == 'NPERIODIC':
            if int(value) != 0:
                raise ValueError('Periodic transformations require a separate audit')
        else:
            raise ValueError('Unsupported mesh section: ' + key)
    if dimension != 2 or not points or not cells or not markers:
        raise ValueError('Incomplete mesh')
    for element in cells + [edge for edges in markers.values() for edge in edges]:
        if any(node not in points for node in element):
            raise ValueError('Element references an absent point')
    return points, cells, markers


def audit_mesh(points, cells, markers):
    """Check pairing using coordinates and outward normals from owning cells."""
    adjacency = defaultdict(list)
    parent = {i: i for i in points}
    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i
    for index, cell in enumerate(cells):
        for a, b in zip(cell, cell[1:] + cell[:1]):
            adjacency[tuple(sorted((a, b)))].append(index)
            parent[find(a)] = find(b)
    components = Counter(find(i) for i in points)
    summaries, edge_maps = {}, {}
    for name in ('upper_nearfield', 'lower_nearfield'):
        edges = markers[name]
        nodes = {i for edge in edges for i in edge}
        by_coords = defaultdict(list)
        for i in nodes:
            by_coords[points[i]].append(i)
        edge_map = defaultdict(list)
        for a, b in edges:
            edge_map[tuple(sorted((points[a], points[b])))].append((a, b))
        edge_maps[name] = edge_map
        summaries[name] = {
            'nodes': len(nodes), 'edges': len(edges),
            'duplicate_coordinates_within_marker': sum(len(v)-1 for v in by_coords.values()),
            'duplicate_geometric_edges': sum(len(v)-1 for v in edge_map.values()),
            'owner_counts': dict(Counter(len(adjacency[tuple(sorted(edge))]) for edge in edges)),
            'x_range': [min(points[i][0] for i in nodes), max(points[i][0] for i in nodes)],
            'y_range': [min(points[i][1] for i in nodes), max(points[i][1] for i in nodes)],
        }
    a_map, b_map = (edge_maps[name] for name in ('upper_nearfield', 'lower_nearfield'))
    common = set(a_map) & set(b_map)
    normal_errors, checked, invalid = [], 0, 0
    def outward(edge):
        owners = adjacency[tuple(sorted(edge))]
        if len(owners) != 1:
            return None
        cell = cells[owners[0]]
        cx = sum(points[i][0] for i in cell)/len(cell)
        cy = sum(points[i][1] for i in cell)/len(cell)
        (ax, ay), (bx, by) = (points[i] for i in edge)
        nx, ny = by-ay, ax-bx
        if math.hypot(nx, ny) == 0:
            return None
        if nx*(cx-(ax+bx)/2) + ny*(cy-(ay+by)/2) > 0:
            nx, ny = -nx, -ny
        return nx, ny
    for key in common:
        if len(a_map[key]) != 1 or len(b_map[key]) != 1:
            invalid += 1
            continue
        na, nb = outward(a_map[key][0]), outward(b_map[key][0])
        if na is None or nb is None:
            invalid += 1
            continue
        normal_errors.append(math.hypot(na[0]+nb[0], na[1]+nb[1])/math.hypot(*na))
        checked += 1
    anodes = {i for e in markers['upper_nearfield'] for i in e}
    bnodes = {i for e in markers['lower_nearfield'] for i in e}
    ac = {points[i] for i in anodes}
    bc = {points[i] for i in bnodes}
    return {
        'points': len(points), 'cells': len(cells),
        'volume_element_counts': dict(Counter(len(c) for c in cells)),
        'connected_components_by_node_id': len(components),
        'component_sizes': sorted(components.values(), reverse=True),
        'markers': summaries, 'shared_node_ids': len(anodes & bnodes),
        'coincident_coordinate_pairs': len(ac & bc),
        'unmatched_coordinates': [len(ac-bc), len(bc-ac)],
        'matched_edges': len(common), 'unmatched_edges': [len(set(a_map)-set(b_map)), len(set(b_map)-set(a_map))],
        'normal_pairs_checked': checked, 'ambiguous_pairs': invalid,
        'max_relative_normal_sum': max(normal_errors) if normal_errors else None,
        'opposed_normal_pairs': sum(x < 1e-12 for x in normal_errors),
        'scope': 'Mesh topology/geometry only; normal opposition is a necessary interface check, not a solver conservation proof',
        'not_run': ['SU2 solver', 'uniform-flow preservation', 'CFD convergence', 'donor-state runtime inspection'],
    }


def mesh_self_test():
    text = '''NDIME= 2
NELEM= 2
5 0 1 2 0
5 3 5 4 1
NPOIN= 6
0 0 0
1 0 1
0 1 2
0 0 3
1 0 4
0 -1 5
NMARK= 2
MARKER_TAG= upper_nearfield
MARKER_ELEMS= 1
3 0 1
MARKER_TAG= lower_nearfield
MARKER_ELEMS= 1
3 3 4
'''
    points, cells, markers = parse_mesh(text)
    good = audit_mesh(points, cells, markers)
    assert good['matched_edges'] == 1 and good['opposed_normal_pairs'] == 1
    assert good['connected_components_by_node_id'] == 2 and good['shared_node_ids'] == 0
    gap = dict(points)
    gap[4] = (1., 0.1)
    assert audit_mesh(gap, cells, markers)['unmatched_edges'] == [1, 1]
    wrong = dict(points)
    wrong[5] = (0., 1.)
    assert audit_mesh(wrong, cells, markers)['opposed_normal_pairs'] == 0
    print('MESH_AUDITOR_SELF_TEST: aligned, gap, and wrong-side fixtures passed; not SU2 tests', flush=True)


def su2():
    mesh_self_test()
    url = 'https://raw.githubusercontent.com/su2code/TestCases/' + MESH_COMMIT + '/' + MESH_PATH
    with urlopen(url, timeout=30) as response:
        raw = response.read(6*1024*1024+1)
    if len(raw) > 6*1024*1024:
        raise RuntimeError('Mesh exceeds read budget')
    blob = hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()
    if blob != MESH_BLOB:
        raise RuntimeError('Mesh Git blob hash mismatch')
    result = audit_mesh(*parse_mesh(raw.decode('utf-8')))
    result.update(mesh_url=url, mesh_commit=MESH_COMMIT, mesh_blob_sha=blob,
                  mesh_sha256=hashlib.sha256(raw).hexdigest(),
                  interpretation='Geometry evidence; no defect/solver-fix claim',
                  ai_disclosure='ChatGPT generated the audit; GitHub Actions executed it.')
    save('su2-mesh.json', result)
    print('SU2_MESH_RESULT ' + json.dumps(result), flush=True)


def openmdao():
    import numpy as np
    import openmdao
    import openmdao.api as om
    target = Path('openmdao-target').resolve()
    head = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=target, check=True,
                          capture_output=True, text=True).stdout.strip()
    if head != OPENMDAO_COMMIT or not Path(openmdao.__file__).resolve().is_relative_to(target):
        raise RuntimeError('Wrong OpenMDAO source checkout/import')
    p = om.Problem(reports=False)
    ivc = om.IndepVarComp()
    ivc.add_output('x', val=20.)
    ivc.add_output('v', val=np.array([-2., 5.]))
    p.model.add_subsystem('ivc', ivc, promotes=['*'])
    p.model.add_subsystem('calc', om.ExecComp(['c=2*x', 'eq=x', 'f=x*x+sum(v*v)'],
                                           v=np.zeros(2)), promotes=['*'])
    p.model.add_design_var('x', lower=10., upper=30., adder=-10., scaler=0.1)
    p.model.add_design_var('v', lower=np.array([-4., 1.]), upper=np.array([0., 9.]),
                           adder=np.array([0., -1.]), scaler=np.array([0.25, 2.]))
    p.model.add_constraint('c', lower=20., upper=60., ref0=20., ref=60.)
    p.model.add_constraint('eq', equals=25., adder=-5., scaler=0.2)
    p.model.add_objective('f')
    p.setup()
    p.run_model()
    data = p.driver.scaling_report(outfile=str(OUT/'driver_scaling_report.html'), show_browser=False, jac=False)
    def plain(obj):
        if isinstance(obj, np.ndarray): return obj.tolist()
        if isinstance(obj, np.generic): return obj.item()
        raise TypeError(type(obj).__name__)
    clean = json.loads(json.dumps(data, default=plain))
    save('openmdao-report-data.json', clean)
    def row(table, name):
        found = [item for item in data[table] if item['name'].split('.')[-1] == name]
        if len(found) != 1:
            raise RuntimeError('Ambiguous/missing report row: '+name)
        return found[0]
    checks = []
    def check(name, actual, expected):
        ok = bool(np.allclose(actual, expected, atol=1e-12, rtol=1e-12))
        checks.append({'name': name, 'actual': np.asarray(actual).tolist(),
                       'expected': expected, 'passed': ok})
    x = row('dv_table', 'x')
    check('scalar scaled endpoints', [x['lower'][0], x['upper'][0]], [0., 2.])
    v = row('dv_table', 'v')
    check('vector element lower endpoints', [c['lower'][0] for c in v['_children']], [-1., 0.])
    check('vector element upper endpoints', [c['upper'][0] for c in v['_children']], [0., 16.])
    c = row('con_table', 'c')
    check('ref/ref0 constraint endpoints', [c['lower'][0], c['upper'][0]], [0., 1.])
    eq = row('con_table', 'eq')
    check('equality target', [eq['equals'][0]], [4.])
    template = target/'openmdao/visualization/scaling_viewer/scaling_table.html'
    relevant = [{'line': i, 'text': line} for i, line in enumerate(template.read_text().splitlines(), 1)
                if re.search(r'lower|upper|equals|visible|checkbox', line, re.I)]
    save('openmdao-template-excerpts.json', relevant)
    result = {'commit': head, 'version': openmdao.__version__, 'python': sys.version,
              'checks': checks, 'passed': sum(c['passed'] for c in checks),
              'failed': sum(not c['passed'] for c in checks),
              'scope': 'Full OpenMDAO model execution and HTML report generation, no source changes',
              'not_run': ['browser rendering', 'full OpenMDAO suite', 'optimization', 'negative-scaler or unit-conversion cases'],
              'interpretation': 'Characterize existing fields before proposing an issue3795 implementation',
              'ai_disclosure': 'ChatGPT generated the probe; GitHub Actions executed it.'}
    save('openmdao-results.json', result)
    print('OPENMDAO_RESULT ' + json.dumps(result), flush=True)
    p.cleanup()
    if result['failed']:
        raise RuntimeError('Report characterization disagrees with analytic expectations')


if __name__ == '__main__':
    OUT.mkdir(exist_ok=True)
    if sys.argv[1:] == ['su2']:
        su2()
    elif sys.argv[1:] == ['openmdao']:
        openmdao()
    elif sys.argv[1:] == ['--self-test']:
        mesh_self_test()
    else:
        raise SystemExit('usage: frontier_wave13.py su2|openmdao|--self-test')
