"""Fork-only read-only reconnaissance; generated by ChatGPT.

No target code execution, upstream writes, automatic policy approval, or bug claims.
A successful run means evidence collection finished, not that candidates are valid.
"""
import base64
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import threading
import time
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

OUT = Path('frontier-results')
LOCK = threading.Lock()
REQUESTS = 0
MAX_REQUESTS = 450
MAX_BYTES = 8 * 1024 * 1024
DEADLINE = time.monotonic() + 600


def get(path, receipts):
    global REQUESTS
    if not path.startswith('/repos/') or '..' in path:
        raise ValueError('Only constructed repository GET paths are supported')
    with LOCK:
        if REQUESTS >= MAX_REQUESTS or time.monotonic() > DEADLINE:
            raise RuntimeError('Scout request/time budget exhausted')
        REQUESTS += 1
    url = 'https://api.github.com' + path
    headers = {'Accept': 'application/vnd.github+json',
               'X-GitHub-Api-Version': '2022-11-28',
               'User-Agent': 'kvnloo-frontier-scout'}
    token = os.environ.get('GH_TOKEN')
    if token:
        headers['Authorization'] = 'Bearer ' + token
    receipt = {'url': url}
    receipts.append(receipt)
    try:
        with urlopen(Request(url, headers=headers, method='GET'), timeout=20) as response:
            receipt['status'] = response.status
            receipt['more_pages'] = 'rel="next"' in response.headers.get('Link', '')
            raw = response.read(MAX_BYTES + 1)
            if len(raw) > MAX_BYTES:
                raise RuntimeError('Response exceeds bounded size')
            return json.loads(raw)
    except HTTPError as error:
        receipt['status'] = error.code
        raise RuntimeError('HTTP ' + str(error.code) + ': ' + path) from None
    except (URLError, TimeoutError) as error:
        receipt['error_type'] = type(error).__name__
        raise RuntimeError('Network read failed: ' + path) from None


def policy_path(path):
    name = Path(path).name.lower()
    return (name.startswith(('contributing', 'ai_policy', 'ai-policy',
                             'artificial-intelligence', 'pull_request_template'))
            or name in ('agents.md', 'claude.md', 'code_of_conduct.md'))


def classify(issue):
    if 'pull_request' in issue:
        return 'EXISTING_PR_REVIEW_NOT_NEW_IMPLEMENTATION'
    if issue.get('state') == 'closed':
        return 'CLOSED_REVALIDATE_OR_REPLACE'
    if issue.get('assignees'):
        return 'COORDINATE_WITH_ASSIGNEE'
    return 'OPEN_REQUIRES_COMMENT_AND_POLICY_REVIEW'


def scout(row):
    repo, a_id, a_title, b_id, b_title = row
    report = {'repository': repo, 'retrieved_at': datetime.now(timezone.utc).isoformat(),
              'requests': [], 'errors': [], 'policies': [], 'tasks': [],
              'policy_gate': 'HUMAN_REVIEW_REQUIRED',
              'limits': ['Only first 100 comments/timeline events per target',
                         'At most 8 repository policy files; inherited policy may remain unknown',
                         'No proof, build, performance, hardware, or contribution-readiness claims']}
    prefix = '/repos/' + repo
    def read(path):
        try:
            return get(path, report['requests'])
        except Exception as error:
            report['errors'].append(str(error))
            return None

    metadata = read(prefix)
    sha = None
    if metadata:
        report['archived'] = metadata.get('archived')
        report['default_branch'] = metadata.get('default_branch')
        ref = read(prefix + '/git/ref/heads/' + quote(metadata['default_branch'], safe=''))
        if ref:
            sha = ref['object']['sha']
            report['head_sha'] = sha
            tree = read(prefix + '/git/trees/' + sha + '?recursive=1')
            if tree:
                report['tree_truncated'] = tree.get('truncated', False)
                paths = [entry['path'] for entry in tree.get('tree', [])
                         if entry.get('type') == 'blob' and policy_path(entry['path'])
                         and not any(part.lower() in ('vendor', 'external', 'third_party', 'externals')
                                     for part in Path(entry['path']).parts)]
                paths.sort(key=lambda path: (len(Path(path).parts), path.lower()))
                report['policy_candidates'] = paths
                report['unread_policy_candidates'] = paths[8:]
                for path in paths[:8]:
                    item = read(prefix + '/contents/' + quote(path, safe='/') + '?ref=' + sha)
                    if not item or item.get('encoding') != 'base64':
                        continue
                    raw = base64.b64decode(item['content'])
                    blob = hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).hexdigest()
                    if blob != item['sha']:
                        report['errors'].append('Policy blob hash mismatch: ' + path)
                        continue
                    text = raw.decode('utf-8')
                    report['policies'].append({'path': path, 'blob_sha': blob,
                        'url': 'https://github.com/' + repo + '/blob/' + sha + '/' + quote(path, safe='/'),
                        'content': text,
                        'ai_signal_lines': [line for line in text.splitlines()
                            if re.search(r'\bAI\b|artificial intelligence|generative|LLM|ChatGPT|Claude|Copilot', line, re.I)]})
    for slot, number, title in [('A', a_id, a_title), ('B', b_id, b_title)]:
        task = {'slot': slot, 'planned_title': title, 'number': number,
                'status': 'UNVERIFIED', 'posting_status': 'NOT_ATTEMPTED'}
        if number is None:
            task.update(status='DISCOVERY_REQUIRED', url='https://github.com/' + repo + '/issues')
        else:
            path = prefix + '/issues/' + str(number)
            issue = read(path)
            if issue:
                task.update(issue=issue, url=issue['html_url'], status=classify(issue))
                task['comments'] = read(path + '/comments?per_page=100')
                task['timeline'] = read(path + '/timeline?per_page=100')
        report['tasks'].append(task)
    output = OUT / (repo.replace('/', '__') + '.json')
    output.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    print(json.dumps({'repo': repo, 'sha': sha,
          'tasks': [task['status'] for task in report['tasks']],
          'policy_files': len(report['policies']), 'errors': len(report['errors'])}), flush=True)
    return report


def self_test():
    checks = [classify({'state': 'closed'}) == 'CLOSED_REVALIDATE_OR_REPLACE',
              classify({'pull_request': {}, 'state': 'open'}) == 'EXISTING_PR_REVIEW_NOT_NEW_IMPLEMENTATION',
              classify({'state': 'open', 'assignees': ['owner']}) == 'COORDINATE_WITH_ASSIGNEE',
              classify({'state': 'open'}) == 'OPEN_REQUIRES_COMMENT_AND_POLICY_REVIEW',
              policy_path('.github/CONTRIBUTING.md'), policy_path('AI_POLICY.md'),
              policy_path('docs/AGENTS.md'), not policy_path('src/gain.py')]
    if not all(checks):
        raise RuntimeError('Scout self-tests failed')
    print('Scout self-tests: 8/8; these are not target-repository tests.')


def main():
    self_test()
    if sys.argv[1:] == ['--self-test']:
        return
    rows = json.loads(Path(__file__).with_name('frontier_manifest.json').read_text())
    if (len(rows) != 20 or len({row[0] for row in rows}) != 20
            or any(not re.fullmatch(r'[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', row[0]) for row in rows)):
        raise RuntimeError('Expected exactly 20 distinct allowlisted repositories')
    OUT.mkdir(exist_ok=True)
    with ThreadPoolExecutor(max_workers=4) as pool:
        reports = list(pool.map(scout, rows))
    counts = {}
    for report in reports:
        for task in report['tasks']:
            counts[task['status']] = counts.get(task['status'], 0) + 1
    summary = {'repositories': len(reports), 'task_lanes': sum(counts.values()),
               'concurrent_readers': 4, 'requests': REQUESTS, 'status_counts': counts,
               'repository_errors': {r['repository']: r['errors'] for r in reports if r['errors']},
               'policy_gate': 'No repository is automatically approved; read captured files and inherited policies',
               'execution': 'Read-only GitHub metadata, policy, issue, and discussion collection',
               'ai_disclosure': 'ChatGPT generated this scout and manifest.'}
    (OUT / 'SUMMARY.json').write_text(json.dumps(summary, indent=2) + '\n')
    lines = ['# Frontier pstack: 20 repos / 40 candidate lanes', '',
             'This is reconnaissance, not proof or policy approval.', '',
             '| Repository | A | B |', '| --- | --- | --- |']
    for report in reports:
        cells = []
        for task in report['tasks']:
            label = str(task['number']) if task['number'] else task['planned_title']
            cells.append('[' + label + '](' + task.get('url', 'https://github.com/' + report['repository']) + ') ' + task['status'])
        lines.append('| ' + report['repository'] + ' | ' + ' | '.join(cells) + ' |')
    (OUT / 'PSTACK.md').write_text('\n'.join(lines) + '\n')
    print('FRONTIER_SUMMARY ' + json.dumps(summary), flush=True)


if __name__ == '__main__':
    main()
