"""Refined fork-only evidence; generated by ChatGPT.

The OpenMDAO lane is EXPECTED-FAILURE verification on unmodified source, not a fix.
The SU2 lane only accepts the mesh's zero/identity periodic entry; nonidentity
transforms are rejected rather than ignored. Neither lane runs a CFD solve.
"""
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from urllib.request import urlopen

import frontier_wave13 as original

OUT = original.OUT


def strip_identity_periodic(text):
    """Validate identity-only trailing metadata before using our 2-D parser."""
    lines = [line.split('%', 1)[0].strip() for line in text.splitlines()
             if line.split('%', 1)[0].strip()]
    entries = [i for i, line in enumerate(lines) if line.startswith('NPERIODIC=')]
    if not entries:
        return text, []
    if len(entries) != 1:
        raise ValueError('Ambiguous periodic sections')
    index = entries[0]
    count = int(lines[index].split('=', 1)[1])
    tail = lines[index+1:]
    if count not in (0, 1) or len(tail) != 4*count:
        raise ValueError('Only absent or single identity periodic metadata is supported')
    records = []
    if count:
        if tail[0].split('=', 1)[0].strip() != 'PERIODIC_INDEX':
            raise ValueError('Invalid periodic index field')
        identifier = int(tail[0].split('=', 1)[1])
        vectors = [list(map(float, line.split())) for line in tail[1:]]
        if identifier != 0 or any(len(v) != 3 or any(x != 0. for x in v) for v in vectors):
            raise ValueError('Nonidentity periodic transform requires a separate audit')
        records.append({'index': identifier, 'center_rotation_translation': vectors,
                        'classification': 'identity-only'})
    return '\n'.join(lines[:index]) + '\n', records


def su2():
    original.mesh_self_test()
    identity = 'NPERIODIC= 1\nPERIODIC_INDEX= 0\n0 0 0\n0 0 0\n0 0 0\n'
    assert len(strip_identity_periodic(identity)[1]) == 1
    try:
        strip_identity_periodic(identity.rsplit('0 0 0', 1)[0] + '1 0 0\n')
    except ValueError:
        pass
    else:
        raise AssertionError('Nonidentity transform was silently accepted')
    url = ('https://raw.githubusercontent.com/su2code/TestCases/'
           + original.MESH_COMMIT + '/' + original.MESH_PATH)
    with urlopen(url, timeout=30) as response:
        raw = response.read(6*1024*1024+1)
    if len(raw) > 6*1024*1024:
        raise RuntimeError('Mesh size budget exceeded')
    blob = hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()
    if blob != original.MESH_BLOB:
        raise RuntimeError('Mesh source hash mismatch')
    text, transforms = strip_identity_periodic(raw.decode('utf-8'))
    result = original.audit_mesh(*original.parse_mesh(text))
    result.update(mesh_url=url, mesh_commit=original.MESH_COMMIT, mesh_blob_sha=blob,
                  mesh_sha256=hashlib.sha256(raw).hexdigest(),
                  periodic_metadata=transforms,
                  ai_disclosure='ChatGPT generated this audit; GitHub Actions executed it.')
    original.save('su2-mesh.json', result)
    print('SU2_MESH_RESULT ' + json.dumps(result), flush=True)


def openmdao():
    """Reproduce the mismatch, and verify scaled current values separately."""
    result = subprocess.run([sys.executable, str(Path(original.__file__).resolve()), 'openmdao'],
                            capture_output=True, text=True, timeout=120)
    (OUT/'baseline-execution.log').write_text(result.stdout + result.stderr)
    data = json.loads((OUT/'openmdao-report-data.json').read_text())
    summary = json.loads((OUT/'openmdao-results.json').read_text())
    if result.returncode != 1 or summary['passed'] != 0 or summary['failed'] != 5:
        raise RuntimeError('Observed baseline changed; inspect evidence before publishing')
    import numpy as np
    def row(table, name):
        values = [r for r in data[table] if r['name'] == name]
        if len(values) != 1:
            raise RuntimeError('Unexpected report rows')
        return values[0]
    scalar = row('dv_table', 'x')
    constraint = row('con_table', 'c')
    np.testing.assert_allclose(scalar['model_val'][0], [20.])
    np.testing.assert_allclose(scalar['driver_val'][0], [1.])
    np.testing.assert_allclose([scalar['lower'][0], scalar['upper'][0]], [10., 30.])
    np.testing.assert_allclose(constraint['model_val'][0], [40.])
    np.testing.assert_allclose(constraint['driver_val'][0], [0.5])
    evidence = {
        'status': 'EXPECTED_BASELINE_MISMATCH_REPRODUCED_NOT_FIXED',
        'requested_scaled_bound_checks': summary['checks'],
        'driver_value_controls': 'passed for scalar design variable and constraint',
        'commit': original.OPENMDAO_COMMIT,
        'source_modified': False,
        'report_example': {'model_value': 20., 'driver_value': 1.,
                           'reported_bounds': [10., 30.], 'scaled_bounds_expected': [0., 2.]},
        'scope': 'Real model/report generation and expected-failure assertions',
        'not_run': summary['not_run'],
        'ai_disclosure': 'ChatGPT generated the characterization; GitHub Actions executed it.'}
    original.save('openmdao-verification.json', evidence)
    print('OPENMDAO_VERIFIED ' + json.dumps(evidence), flush=True)


if __name__ == '__main__':
    OUT.mkdir(exist_ok=True)
    if sys.argv[1:] == ['su2']:
        su2()
    elif sys.argv[1:] == ['openmdao']:
        openmdao()
    else:
        raise SystemExit('usage: frontier_wave13_verify.py su2|openmdao')
